# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greyscaler', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/'),
        ),
    ]
